version: '3'
services:
  web:
    build: docker/web/
    volumes:
      - ./web:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    working_dir: /app
    env_file:
      - docker/web/.env
    ports:
      - 5000:5000